language: common-lisp

addons:
  postgresql: "9.3"

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl
    - LISP=clisp

matrix:
  allow_failures:
    - env: LISP=clisp

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

before_script:
  - mysql -uroot -e 'GRANT ALL ON *.* TO nobody@"localhost" IDENTIFIED BY "nobody"'
  - mysql -uroot -e 'CREATE DATABASE `integral_test`'
  - psql -c 'create database "integral_test";' -U postgres
  - psql -c "CREATE USER nobody WITH PASSWORD 'nobody';" -U postgres
  - git clone https://github.com/fukamachi/cl-dbi ~/lisp/cl-dbi

script:
  - cl -l prove -e '(or (prove:run :integral-test) (uiop:quit -1))'
